mmates:
  sherdog:
    selector:
      fighter:
        association: .association-class  span[itemprop="name"]
        wins-totals: .winloses.win span:nth-child(2)
        losses-totals: .winloses.lose span:nth-child(2)
server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mmates_sherdog_collector
springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
  packages-to-scan: com.georgeisaev.mmatescollectorsherdog.controller
  swagger-ui:
    path: /swagger-doc/swagger-ui.html